---
# file: playbook-alt.yml

# pinned to a release because
# when you download zips/tarballs
# the paths get a little funky

- name: Special release playbook for zip/tarball downloads.
  hosts: all
  roles:
    - pngnx23299-0.23.42-alpha
