# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/apache2.yml

# Tweaks to default Apache install for use with FreePBX GUI.

- name: Increase Apache PHP max upload size.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^upload_max_filesize'
    line: 'upload_max_filesize = 120M'

- name: Increase Apache PHP memory limit.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: '^memory_limit'
    line: 'memory_limit = 1256M'

- name: Change Apache to run as Asterisk user.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/apache2/envvars
    regexp: '^export APACHE_RUN_USER'
    line: 'export APACHE_RUN_USER=asterisk'

- name: Change Apache to run as Asterisk group.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/apache2/envvars
    regexp: '^export APACHE_RUN_GROUP'
    line: 'export APACHE_RUN_GROUP=asterisk'

- name: Let FreePBX override permissions.
  become: yes
  ansible.builtin.replace:
    path: /etc/apache2/apache2.conf
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'

- name: Enable Apache rewrite module.
  become: yes
  community.general.apache2_module:
    state: present
    name: rewrite

- name: Restart Apache.
  become: yes
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true

- name: Remove the default index.html because FreePBX will replace it with index.php.
  become: yes
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

