# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/bigstar.yml

# Downloads, builds, and (if do_asterisk_install is true) installs Asterisk from source.

- name: Make a place for the Asterisk source.
  when: pngnx_new_src
  ansible.builtin.tempfile:
    suffix: ".asterisk-{{ pngnx_asterisk_version }}"
    state: directory
  register: tmpast

- name: Download Asterisk source.
  when: pngnx_new_src
  ansible.builtin.get_url:
    url: "{{ pngnx_asterisk_urlbase }}/{{ pngnx_asterisk_tarball }}"
    dest: "{{ tmpast.path }}/{{ pngnx_asterisk_tarball }}"
    checksum: "{{ pngnx_asterisk_checksum }}"
    mode: 0644

- name: Unarchive Asterisk source.
  when: pngnx_new_src
  ansible.builtin.unarchive:
    src: "{{ tmpast.path }}/{{ pngnx_asterisk_tarball }}"
    dest: "{{ tmpast.path }}"
    remote_src: true

- name: Copy Asterisk source from temp directory to target install directory.
  become: true
  when: pngnx_new_src
  ansible.builtin.copy:
    src: "{{ tmpast.path }}/asterisk-{{ pngnx_asterisk_version }}"
    dest: "{{ pngnx_build_target }}"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

- name: Copy Asterisk tarball from temp directory to target install directory.
  become: true
  when: pngnx_new_src
  ansible.builtin.copy:
    src: "{{ tmpast.path }}/{{ pngnx_asterisk_tarball }}"
    dest: "{{ pngnx_build_target }}"
    remote_src: true
    mode: 0644

- name: Clean previous Asterisk build. Might not have been one so ignore any errors.
  when: pngnx_new_src or pngnx_clean_src
  ansible.builtin.command: /usr/bin/make -i distclean
  args:
    chdir: "{{ pngnx_asterisk_target }}"
  register: fail_distclean
  failed_when: "fail_distclean.rc < 0"

- name: Specify some default build options.
  become: true
  ansible.builtin.copy:
    src: asterisk-{{ pngnx_asterisk_major }}.makeopts
    dest: /etc/asterisk.makeopts
    mode: 0644

- name: Might not need all these defaults. (But FreePBX uses file-based VoiceMail.)
  become: true
  when: pngnx_voicemail_type is not defined or pngnx_voicemail_type == "files"
  ansible.builtin.lineinfile:
    path: /etc/asterisk.makeopts
    regexp: '^MENUSELECT_OPTS_app_voicemail'
    state: absent

- name: Download MP3 source - per Asterisk contrib/scripts/get_mp3_source.sh file. Ignored if already done.
  ansible.builtin.command: ./contrib/scripts/get_mp3_source.sh
  args:
    chdir: "{{ pngnx_asterisk_target }}"
  ignore_errors: true

# TODO: ansible.builtin.command: ./configure --libdir=/lib/{{ ansible_architecture }}-linux-gnu --with-pjproject-bundled --with-jansson-bundled
- name: Configure Asterisk source - version 18.
  when: pngnx_asterisk_major == 18
  ansible.builtin.command: ./configure --with-pjproject-bundled --with-jansson-bundled
  args:
    chdir: "{{ pngnx_asterisk_target }}"

- name: Configure Asterisk source - version 20.
  when: pngnx_asterisk_major == 20
  ansible.builtin.command: ./configure --with-pjproject-bundled --with-jansson-bundled
  args:
    chdir: "{{ pngnx_asterisk_target }}"

- name: Configure Asterisk source - version 21.
  when: pngnx_asterisk_major == 21
  ansible.builtin.command: ./configure --with-pjproject-bundled --with-jansson-bundled --with-libjwt-bundled
  args:
    chdir: "{{ pngnx_asterisk_target }}"

- name: Make the menuselect.makeopts so the Addons can be added.
  ansible.builtin.command: /usr/bin/make menuselect.makeopts
  args:
    chdir: "{{ pngnx_asterisk_target }}"

- name: Fix-up the Asterisk Addons so they get built.
  ansible.builtin.command: ./menuselect/menuselect --enable-category MENUSELECT_ADDONS menuselect.makeopts
  args:
    chdir: "{{ pngnx_asterisk_target }}"

- name: Build Asterisk from source. Threaded make.
  ansible.builtin.command: /usr/bin/nice -n {{ nicely | default(0) }} /usr/bin/make -j {{ ansible_processor_vcpus | default(2) }} all
  args:
    chdir: "{{ pngnx_asterisk_target }}"
    creates: "{{ pngnx_asterisk_target }}/main/asterisk"

- name: Build Asterisk from source. Single make. Sometimes needed if threaded make fails due to improper ordering of objects between threads.
  ansible.builtin.command: /usr/bin/make all
  args:
    chdir: "{{ pngnx_asterisk_target }}"
    creates: "{{ pngnx_asterisk_target }}/main/asterisk"

- name: Install Asterisk.
  become: true
  when: pngnx_do_asterisk_install
  ansible.builtin.command: /usr/bin/make install
  args:
    chdir: "{{ pngnx_asterisk_target }}"
