# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/catbert.yml

# Handles Human and Robot Resource issues such as usernames and permissions.
# Don't get too carried away because the FreePBX install changes lots of permissions itself.

- name: Make asterisk group.
  become: true
  ansible.builtin.group:
    name: asterisk
    state: present

- name: Make asterisk user.
  become: true
  ansible.builtin.user:
    name: asterisk
    state: present
    groups: asterisk
    shell: /usr/sbin/nologin
    home: /var/lib/asterisk

- name: Make pbx-bots group.
  become: true
  ansible.builtin.group:
    name: pbx-bots
    state: present

- name: Put current user in some extra groups.
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: asterisk,www-data,pbx-bots,sudo
    append: true

- name: Make sure some directories exist.
  become: true
  ignore_errors: true
  ansible.builtin.file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0750
    recurse: "{{ item.recurse }}"
  loop:
    - { dir: "/etc/asterisk",               owner: "asterisk", group: "asterisk", recurse: "yes" }
    - { dir: "/var/lib/asterisk",           owner: "asterisk", group: "asterisk", recurse: "no" }

- name: Change ownership on certain files and also touch them.
  become: true
  ignore_errors: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: asterisk
    group: asterisk
    mode: 0750
    state: touch
  loop:
    - /etc/asterisk/cdr.conf
    - /etc/asterisk/modules.conf
    - /var/lib/asterisk/astdb.sqlite3

- name: Change ownership on certain directories and make sure they exist.
  become: true
  ignore_errors: true
  ansible.builtin.file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0750
    recurse: "{{ item.recurse }}"
  loop:
    - { dir: "/etc/asterisk",               owner: "asterisk", group: "asterisk", recurse: "yes" }
    - { dir: "/var/lib/asterisk/sounds",    owner: "asterisk", group: "asterisk", recurse: "yes" }
    - { dir: "/var/lib/asterisk",           owner: "asterisk", group: "asterisk", recurse: "no" }
    - { dir: "/var/log/asterisk",           owner: "asterisk", group: "pbx-bots", recurse: "yes" }
    - { dir: "/var/spool/asterisk",         owner: "asterisk", group: "asterisk", recurse: "yes" }
    - { dir: "/var/spool/asterisk/monitor", owner: "asterisk", group: "pbx-bots", recurse: "yes" }
    - { dir: "/var/spool/asterisk",         owner: "asterisk", group: "pbx-bots", recurse: "no" }

- name: Copy default main configuration file for Asterisk in to /etc/asterisk/. Do not overwrite if already something there.
  become: true
  ansible.builtin.copy:
    src: "{{ pngnx_asterisk_target }}/configs/samples/asterisk.conf.sample"
    dest: /etc/asterisk/asterisk.conf
    force: false
    owner: root
    group: asterisk
    mode: 0750
    remote_src: true

- name: Check if we are dealing with the default Asterisk configuration file. Part 1.
  ansible.builtin.stat:
    path: "{{ pngnx_asterisk_target }}/configs/samples/asterisk.conf.sample"
  register: st1

- name: Check if we are dealing with the default Asterisk configuration file. Part 2.
  become: true
  ansible.builtin.stat:
    path: /etc/asterisk/asterisk.conf
  register: st2

- name: Modify the default configuration file for Asterisk.
  become: true
  when: st1.stat.checksum == st2.stat.checksum
  ansible.builtin.replace:
    path: /etc/asterisk/asterisk.conf
    regexp: '^\[directories\]\(!\)'
    replace: '[directories]'

