# SPDX-FileCopyrightText: 2024 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/deb-repo-sng.yml

- name: Setup the Sangoma Debian Repository the deb822 way.
  become: true
  ansible.builtin.copy:
    src: 20-sangoma-fpbx-repository-prod.sources
    dest: /etc/apt/sources.list.d/

# TODO: warn the user per https://wiki.debian.org/DebianRepository/UseThirdParty (Standard pinning section)
- name: Prioritize the repo to (potentially) overwrite Debian distro packages.
  become: true
  ansible.builtin.template:
    src: 99sangoma-fpbx-repository.j2
    dest: /etc/apt/preferences.d/99-sangoma-fpbx-repository
