# SPDX-FileCopyrightText: 2024 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/debrepo-sng.yml

# wget -qO - https://deb.freepbx.org/gpg/aptly-pubkey.asc | gpg --armor --export
- name: Setup the Sangoma Debian Repo the deb822 way.
  become: true
  ansible.builtin.copy:
    src: 00-sangoma-fpbx-repository.sources
    dest: /etc/apt/sources.list.d/

# TODO: warn the user per https://wiki.debian.org/DebianRepository/UseThirdParty (Standard pinning section)
- name: Prioritize the repo to (potentially) overwrite Debian distro packages.
  become: true
  ansible.builtin.template:
    src: 99sangoma-fpbx-repository.j2
    dest: /etc/apt/preferences.d/99-sangoma-fpbx-repository
