# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/firewall-ssh.yml

# Maybe counts as application-level firewalling...

- name: Check if SSH key exists as file that needs extra lookup step.
  when: pngnx_installer_sshpubkey is defined
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ pngnx_installer_sshpubkey }}"
  register: pubkey

- name: Allow SSH with ONLY the authorized key. For installer account.
  when:
    - pngnx_installer_sshpubkey is defined
    - not pubkey.stat.exists
  ansible.posix.authorized_key:
    exclusive: true
    state: present
    user: "{{ ansible_user_id }}"
    key: "{{ pngnx_installer_sshpubkey }}"

- name: Allow SSH with ONLY the authorized key. For installer account. Extra lookup step.
  when:
    - pngnx_installer_sshpubkey is defined
    - pubkey.stat.exists
  ansible.posix.authorized_key:
    exclusive: true
    state: present
    user: "{{ ansible_user_id }}"
    key: "{{ lookup('file', pngnx_installer_sshpubkey) }}"

- name: Disallow SSH for root user.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/pngnx23299.conf
    regexp: '^PermitRootLogin '
    line: 'PermitRootLogin no'
    create: true

- name: Limit SSH access to current user via AllowUsers line.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/pngnx23299.conf
    regexp: "^AllowUsers "
    line: "AllowUsers {{ ansible_user_id }}"

- name: Changing SSH port number.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/pngnx23299.conf
    regexp: "^Port "
    line: "Port {{ pngnx_ssh_port|default('22') }}"

- name: Shorten time allowed for SSH login windows.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/pngnx23299.conf
    regexp: '^LoginGraceTime '
    line: 'LoginGraceTime 55'

- name: Disable X11Forwarding over SSH.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/pngnx23299.conf
    regexp: '^X11Forwarding '
    line: 'X11Forwarding no'

- name: Disallow empty passwords over SSH.
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/pngnx23299.conf
    regexp: '^PermitEmptyPasswords '
    line: 'PermitEmptyPasswords no'

- name: Disallow password auth and force public keys.
  become: yes
  when:
    - pngnx_installer_sshpubkey is defined
    - not pngnx_allow_ssh_passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/pngnx23299.conf
    regexp: '^PasswordAuthentication '
    line: 'PasswordAuthentication no'

- name: Allow password auth - in addition to keys.
  become: yes
  when: pngnx_allow_ssh_passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/pngnx23299.conf
    regexp: '^PasswordAuthentication '
    line: 'PasswordAuthentication yes'

- name: Restarting SSH to pick up the changes. CHECK THAT YOUR SSH STILL WORKS!
  become: yes
  ansible.builtin.service:
    name: sshd
    state: restarted

