# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/freepbx-edge-basic.yml

# The minimal FreePBX modules that let you send and receive some calls to and from some extensions.
# Useful for 3rd-party module development for the next major release before it is released :)

- name: Make a place for the FreePBX source.
  when: new_src
  ansible.builtin.tempfile:
    suffix: ".{{ freepbx_edge_basename }}"
    state: directory
  register: tmpedge

- name: Download FreePBX source.
  when: new_src
  ansible.builtin.get_url:
    url: "{{ freepbx_edge_urlbase }}/{{ freepbx_edge_tarball }}"
    dest: "{{ tmpedge.path }}"

- name: Unarchive FreePBX source.
  when: new_src
  ansible.builtin.unarchive:
    src: "{{ tmpedge.path }}/{{ freepbx_edge_tarball }}"
    dest: "{{ tmpedge.path }}"
    remote_src: true

- name: Copy FreePBX source from temp directory to target install directory.
  become: yes
  when: new_src
  ansible.builtin.copy:
    src: "{{ tmpedge.path }}/freepbx"
    dest: "{{ build_target }}"
    remote_src: true

- name: Copy FreePBX tarball from temp directory to target install directory.
  become: yes
  when: new_src
  ansible.builtin.copy:
    src: "{{ tmpedge.path }}/{{ freepbx_edge_tarball }}"
    dest: "{{ build_target }}"
    remote_src: true

- name: Start Asterisk using FreePBX scripts.
  become: yes
  ansible.builtin.command: ./start_asterisk start
  args:
    chdir: "{{ freepbx_edge_target }}"

# the PATH modification is needed to support use of runuser in the install script
# TODO: maybe: use --dev-links
- name: Install FreePBX. Ignoring errors because even with install script -q option there is a bunch of output.
  become: yes
  ansible.builtin.command: ./install -n -f -q
  args:
    chdir: "{{ freepbx_edge_target }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  ignore_errors: true

- name: Install the basic local modules. As a group.
  become: yes
  ansible.builtin.command: /sbin/fwconsole ma install {{ freepbx_basic_modules|flatten }}
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  ignore_errors: true
   
- name: Reload FreePBX.
  become: yes
  ansible.builtin.command: /sbin/fwconsole reload
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  ignore_errors: true
   
- name: Restart FreePBX.
  become: yes
  ansible.builtin.command: /sbin/fwconsole restart
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  ignore_errors: true
   
