# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/freepbx-tarball.yml

# This might work as soon as the tarball is out.

- name: Download FreePBX source.
  when: new_src
  ansible.builtin.get_url:
    url: "{{ freepbx_urlbase }}/{{ freepbx_tarball }}"
    dest: /tmp

- name: Unarchive FreePBX source.
  when: new_src
  ansible.builtin.unarchive:
    src: "/tmp/{{ freepbx_tarball }}"
    dest: /tmp
    remote_src: true

- name: Copy FreePBX source from temp directory to target install directory.
  become: yes
  when: new_src
  ansible.builtin.copy:
    src: /tmp/freepbx-{{ freepbx_version }}
    dest: "{{ build_target }}"
    remote_src: true

- name: Copy FreePBX tarball from temp directory to target install directory.
  become: yes
  when: new_src
  ansible.builtin.copy:
    src: /tmp/{{ freepbx_tarball }}
    dest: "{{ build_target }}"
    remote_src: true

- name: Start Asterisk using FreePBX scripts.
  become: yes
  ansible.builtin.command: ./start_asterisk start
  args:
    chdir: "{{ freepbx_git_target }}/framework"

# the PATH modification is needed to support use of runuser in the install script
# ignoring errors because even with install script -q option there is a bunch of output
- name: Install FreePBX framework.
  become: yes
  ansible.builtin.command: ./install --dev-links -n -f -q
  args:
    chdir: "{{ freepbx_git_target }}/framework"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  ignore_errors: true

- name: Fix perms on PM2 it is a bugger.
  become: yes
  ansible.builtin.file:
    path: /var/www/html/admin/modules/pm2
    owner: asterisk
    group: asterisk
    recurse: true

- name: Install the local modules.
  become: yes
  ansible.builtin.command: /sbin/fwconsole ma installlocal
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
   
- name: Reload FreePBX.
  become: yes
  ansible.builtin.command: /sbin/fwconsole reload
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
   
- name: Restart FreePBX.
  become: yes
  ansible.builtin.command: /sbin/fwconsole restart
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
   
