# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/freepbx-git-plus.yml

# Do the basic modules first, then extra, and then add these for even more features.

- name: Make top temp directory to hold the modules.
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.tempfile:
    suffix: ".{{ pngnx_freepbx_git_basename }}-plus"
    state: directory
  register: tmpfpgit

- name: Make sub temp directories to hold the modules.
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.file:
    path: "{{ tmpfpgit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}"
    state: directory
  with_items: "{{ pngnx_freepbx_plus_modules }}"

- name: Download FreePBX module sources from main FREEPBX git repo as zip files.
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.get_url:
    url: "{{ pngnx_freepbx_git_urlbase }}/{{ item }}/{{ pngnx_freepbx_git_urlpost }}"
    dest: "{{ tmpfpgit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}.zip"
  with_items: "{{ pngnx_freepbx_plus_modules }}"
  ignore_errors: true

- name: Unarchive FreePBX module sources.
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.unarchive:
    src: "{{ tmpfpgit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}.zip"
    dest: "{{ tmpfpgit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}"
    remote_src: true
  with_items: "{{ pngnx_freepbx_plus_modules }}"
  ignore_errors: true

- name: Copy FreePBX module sources from temp directory to target install directory.
  become: true
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.copy:
    src: "{{ tmpfpgit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}"
    dest: "{{ pngnx_freepbx_git_target }}"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items: "{{ pngnx_freepbx_plus_modules }}"
  ignore_errors: true

- name: Copy FreePBX module zip files from temp directory to target install directory.
  become: true
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.copy:
    src: "{{ tmpfpgit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}.zip"
    dest: "{{ pngnx_freepbx_git_target }}"
    remote_src: true
  with_items: "{{ pngnx_freepbx_plus_modules }}"
  ignore_errors: true

- name: Copy in the modules from usr/src to var/www.
  become: true
  ansible.builtin.copy:
    src: "{{ pngnx_freepbx_git_target }}/{{ item }}/{{ item }}-release-{{ pngnx_freepbx_git_version }}/"
    dest: /var/www/html/admin/modules/{{ item }}/
    remote_src: true
  with_items: "{{ pngnx_freepbx_plus_modules }}"
  ignore_errors: true

- name: Install the local modules. One-by-one. Ignore errors.
  become: true
  ansible.builtin.command:
    argv:
      - /sbin/fwconsole
      - ma
      - install
      - "{{ item }}"
  with_items: "{{ pngnx_freepbx_plus_modules }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
  ignore_errors: true

- name: Reload FreePBX.
  become: true
  ansible.builtin.command:
    argv:
      - /sbin/fwconsole
      - reload
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"

- name: Restart FreePBX.
  become: true
  ansible.builtin.command:
    argv:
      - /sbin/fwconsole
      - restart
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
