# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/freepbx-edge-extra.yml

# Do the basic modules first and then add these for more features.

- name: Install the extra local modules. As a group.
  become: true
  ansible.builtin.command:
    argv:
      - /sbin/fwconsole
      - ma
      - install
      - "{{ pngnx_freepbx_extra_modules | flatten }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"

- name: Reload FreePBX.
  become: true
  ansible.builtin.command:
    argv:
      - /sbin/fwconsole
      - reload
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"

- name: Restart FreePBX.
  become: true
  ansible.builtin.command:
    argv:
      - /sbin/fwconsole
      - restart
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
