# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/freepbx-git-extra.yml

# Do the basic modules first and then add these for more features.

- name: Make top temp directory to hold the modules.
  when: pngnx_new_src
  ansible.builtin.tempfile:
    suffix: ".{{ pngnx_freepbx_git_basename }}-extra"
    state: directory
  register: tmpfegit

- name: Make sub temp directories to hold the modules.
  when: pngnx_new_src
  ansible.builtin.file:
    path: "{{ tmpfegit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}"
    state: directory
  with_items: "{{ pngnx_freepbx_extra_modules }}"

- name: Download FreePBX module sources from main FREEPBX git repo as zip files.
  when: pngnx_new_src
  ansible.builtin.get_url:
    url: "{{ pngnx_freepbx_git_urlbase }}/{{ item }}/{{ pngnx_freepbx_git_urlpost }}"
    dest: "{{ tmpfegit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}.zip"
  with_items: "{{ pngnx_freepbx_extra_modules }}"

- name: Unarchive FreePBX module sources.
  when: pngnx_new_src
  ansible.builtin.unarchive:
    src: "{{ tmpfegit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}.zip"
    dest: "{{ tmpfegit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}"
    remote_src: true
  with_items: "{{ pngnx_freepbx_extra_modules }}"

- name: Copy FreePBX module sources from temp directory to target install directory.
  become: true
  when: pngnx_new_src
  ansible.builtin.copy:
    src: "{{ tmpfegit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}"
    dest: "{{ pngnx_freepbx_git_target }}"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  with_items: "{{ pngnx_freepbx_extra_modules }}"

- name: Copy FreePBX module zip files from temp directory to target install directory.
  become: true
  when: pngnx_new_src
  ansible.builtin.copy:
    src: "{{ tmpfegit.path }}/{{ pngnx_freepbx_git_basename }}/{{ item }}.zip"
    dest: "{{ pngnx_freepbx_git_target }}"
    remote_src: true
  with_items: "{{ pngnx_freepbx_extra_modules }}"

- name: Copy in the modules from usr/src to var/www.
  become: true
  ansible.builtin.copy:
    src: "{{ pngnx_freepbx_git_target }}/{{ item }}/{{ item }}-release-{{ pngnx_freepbx_git_version }}/"
    dest: /var/www/html/admin/modules/{{ item }}/
    remote_src: true
  with_items: "{{ pngnx_freepbx_extra_modules }}"
  ignore_errors: true

- name: Install the extra local modules. All that were downloaded, as a group.
  become: true
  ansible.builtin.command: /sbin/fwconsole ma installlocal
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"

- name: Reload FreePBX.
  become: true
  ansible.builtin.command: /sbin/fwconsole reload
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"

- name: Restart FreePBX.
  become: true
  ansible.builtin.command: /sbin/fwconsole restart
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin:/usr/sbin"
