# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/logs-rotate.yml

- name: Copy over the templated rotation policies.
  become: true
  ansible.builtin.template:
    src: logrotate.pngnx.j2
    dest: /etc/logrotate.d/pngnx
  
