# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# pngnx23299 -- An Ansible Role for installing FreePBX 17 on Debian 12
#
# This file is part of pngnx23299.
#
# pngnx23299 is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# pngnx23299 is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# pngnx23299. If not, see <https://www.gnu.org/licenses/>. 
#

---
# file: roles/pngnx23299/tasks/main.yml

# Starts the installation. Asks to confirm and then off to the races.

- name: Howdy :)
  tags: [ confirm ]
  ansible.builtin.debug:
    msg:
     - "**************************************************************************"
     - "*                                                                        *"
     - "* Welcome to pngnx23299!  Copyright 2023 GPLv3+ by Penguin PBX Solutions *"
     - "*                                                                        *"
     - "* This Ansible Role helps install software written/copyright by others,  *"
     - "* mainly Asterisk 20 and FreePBX 17 (BETA / GIT) on Debian 12, so mostly *"
     - "* open source, but can be told to install some non-free codecs/firmware. *"
     - "*                                                                        *"
     - "*            BEFORE YOU BEGIN, PLEASE ASK YOURSELF IF YOU:               *"
     - "*                                                                        *"
     - "* 1. Want to test the most recent FreePBX 17, BETA or direct from GIT?   *"
     - "* 2. Got 5GB of disk space free on your brand new Debian 12 testing box? *"
     - "* 3. Can SSH into the box and su to root? (Check your ~/.ssh/config)     *"
     - "* 4. Okay with blowing away everything on the target?  REALLY??? Backup? *"
     - "* 5. Accept full liability/responsibility for everything that happens?   *"
     - "*                                                                        *"
     - "*       DO NOT PROCEED UNTIL YOU CAN ANSWER YES TO ALL THE ABOVE.        *"
     - "*                                                                        *"
     - "*  System may reboot automatically if kernel was updated in first steps. *"
     - "*  Role will continue to run if target comes back online in 10 minutes.  *"
     - "*  But, you may need to manually restart the target eg. Virtual Machine. *"
     - "*                                                                        *"
     - "* WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING *" 
     - "*     You are installing bleeding-edge GIT pulled development code!      *"
     - "*    Running Online Module Updates will not work very easily at all.     *"
     - "*       Some modules may not work without some serious hammering.        *"
     - "*       Please do not use outside of your test bench environment.        *"
     - "* WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING *" 
     - "*                                                                        *"
     - "**************************************************************************"

- name: Testing. Testing. Check. Check.
  ansible.builtin.include_tasks: tests.yml
  tags: [ never, tests ]

- name: Checking if Debian 12 target.
  tags: [ confirm ]
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version == "12"
    fail_msg: "Install terminated. Role currently only works with Debian 12, sorry."
    success_msg: "{{ ansible_lsb.description }} detected on {{ ansible_host }}. Great!"

- name: Prompting to confirm installation.
  tags: [ confirm ]
  ansible.builtin.pause:
    prompt: Please read the *BOXED WARNING* above and type YES to confirm installation, then press Enter.
  register: promptconfirmed
  run_once: true

- name: Checking for confirmation.
  tags: [ confirm ]
  ansible.builtin.assert:
    that: promptconfirmed.user_input == "YES"
    fail_msg: "Install terminated. You did not type YES. So, Adios!"
    success_msg: "Confirmation accepted. You typed YES. Install proceeding. Vamanos!"

- name: Uninstall only when tag provided.
  ansible.builtin.include_tasks: uninstall.yml
  tags: [ never, uninstall ]
 
- name: Packages.
  ansible.builtin.include_tasks:
    file: packages.yml
    apply:
      tags: packages
  tags: packages

- name: Database.
  ansible.builtin.include_tasks:
    file: mariadb.yml
    apply:
      tags: db
  tags: db

- name: DAHDI hardware installation.
  ansible.builtin.include_tasks:
    file: dahdi.yml
    apply:
      tags: dahdi
  tags: dahdi

- name: DAHDI non-free firmware installation.
  tags: [ never, nonfree ]
  ansible.builtin.include_tasks: dahdi.yml

- name: LIBPRI installation.
  ansible.builtin.include_tasks: libpri.yml

- name: Asterisk installation.
  ansible.builtin.include_tasks:
    file: bigstar.yml
    apply:
      tags: star
  tags: star

- name: Additonal non-free codecs.
  tags: [ never, nonfree ]
  ansible.builtin.include_tasks: codecs.yml

- name: Adjusting users, groups and permissions; and some files needed for FreePBX install.
  ansible.builtin.include_tasks:
    file: catbert.yml
    apply:
      tags: catbert
  tags: catbert

- name: Apache2 installation.
  ansible.builtin.include_tasks:
    file: apache2.yml
    apply:
      tags: apache
  tags: apache

- name: VLAN with dnsmasq and resolvconf support for PBX to drive the phones.
  tags: vlan
  when: pngnx_phone_vlans is defined
  ansible.builtin.include_tasks:
    file: vlan-bossmode.yml
    apply:
      tags: vlan

- name: ChronyD for PBX to tell the time, if asked.
  tags: drwho
  ansible.builtin.include_tasks:
    file: chrony.yml
    apply:
      tags: drwho

- name: Firewall protection.
  tags: firewall
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: firewall
  loop:
    - firewall-qos-iptables-nft.yml
    - firewall-ufw.yml
    - firewall-fail2ban.yml
    - firewall-ssh.yml

### not used by FreePBX
###- name: SystemD start up for Asterisk.
###  ansible.builtin.include_tasks: systemd-asterisk.yml

- block:
  - name: Installing FreePBX.
    ansible.builtin.debug:
      msg: pngnx_freepbx_upstream set to {{ pngnx_freepbx_upstream }}
  - name: Basic FreePBX from either EDGE or GIT. Enough to register phones and test call the telco.
    ansible.builtin.include_tasks: freepbx-{{ pngnx_freepbx_upstream }}-basic.yml
  - name: Extra FreePBX modules from either EDGE or GIT. Beyond Basic. Includes CDRs, Logs, IVRs, and more.
    ansible.builtin.include_tasks:
      file: freepbx-{{ pngnx_freepbx_upstream }}-extra.yml
      apply:
        tags: extra
    tags: extra
  - name: Plus the rest of the FreePBX modules from either EDGE or GIT. Beyond Basic and Extra.
    ansible.builtin.include_tasks:
      file: freepbx-{{ pngnx_freepbx_upstream }}-plus.yml
      apply:
        tags: plus
    tags: plus
  - name: Patches. Currently just one PHP 8.2 deprecation is patched for outbound routing.
    ansible.builtin.include_tasks: patches.yml
  - name: FreePBX database customizations.
    ansible.builtin.include_tasks: freepbx-polish.yml
  # FreePBX uses fwconsole to start Asterisk and several other things
  - name: SystemD start up for FreePBX.
    ansible.builtin.include_tasks: systemd-freepbx.yml
  tags: gui

- block:
  - name: Phone provisioning with NGINX proxy in front of the Asterisk HTTP port.
    ansible.builtin.include_tasks: nginx.yml
    when: pngnx_phoneprov_polycom is defined
  - name: Phone provisioning template files.
    ansible.builtin.include_tasks: phoneprov.yml
    when: pngnx_phoneprov_polycom is defined
  tags: phoneprov

# TODO: expand to more places
- name: Log rotation policies for things in /var/log/asterisk/ tree.
  tags: logs-rotate
  ansible.builtin.include_tasks:
    file: logs-rotate.yml
    apply:
      tags: logrotate

- name: Did you try turning it off and then back on again?
  become: yes
  ansible.builtin.service:
    name: "{{ pngnx_freepbx_systemd_name }}"
    enabled: yes   
    state: restarted

- name: W00t!
  ansible.builtin.debug:
    msg:
     - "**************************************************************************"
     - "*                                                                        *"
     - "* Test new SSH connection! Open FreePBX GUI in your web browser! Enjoy!  *"
     - "*                                                                        *"
     - "*   YOU MUST IMMEDIATELY CONNECT TO THE WEB GUI AND SET YOUR PASSWORDS.  *"
     - "*   YOU MUST IMMEDIATELY CONNECT TO THE WEB GUI AND SET YOUR PASSWORDS.  *"
     - "*                                                                        *"
     - "* You'll probably see some warnings about Unsigned and Tampered Modules. *"
     - "*                                                                        *"
     - "*                DON'T PANIC. Just be careful :)                         *"
     - "*                                                                        *"
     - "* WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING *" 
     - "*       You are running bleeding-edge GIT pulled development code!       *"
     - "*    Running Online Module Updates will not work very easily at all.     *"
     - "*       Some modules may not work without some serious hammering.        *"
     - "*        THIS IS YOUR FREE GIFT/JOKE WITH ABSOLUTELY NO WARRANTY.        *"
     - "* WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING! WARNING *" 
     - "*                                                                        *"
     - "**************************************************************************"
     - ""
     - " GUI may be at   http://{{ ansible_host }}   OR   http://{{ ansible_default_ipv4['address'] }}"
     - ""

