# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/mariadb.yml

# Configure MariaDB/MYSQL in a way that FreePBX can handle.

- name: Make MYSQL Great Again.
  become: true
  ansible.builtin.ini_file:
    path: /etc/mysql/mariadb.conf.d/99-pngnx.cnf
    section: mysqld
    option: "{{ item.k }}"
    value: "{{ item.v }}"
    no_extra_spaces: true
  loop:
    - { k: "sql_mode",     v: "" }
    - { k: "bind-address", v: "127.0.0.1,::" }

- name: Restart MariaDB (MYSQL).
  become: true
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: Prep odbc.ini for FreePBX ODBC connection.
  become: true
  ansible.builtin.ini_file:
    path: /etc/odbc.ini
    section: MySQL-asteriskcdrdb
    option: "{{ item.k }}"
    value: "{{ item.v }}"
    no_extra_spaces: true
  loop:
    - { k: "Description", v: "MySQL connection to 'asteriskcdrdb' database" }
    - { k: "driver",      v: "MariaDB Unicode" }
    - { k: "server",      v: "localhost" }
    - { k: "database",    v: "asteriskcdrdb" }
    - { k: "Port",        v: "3306" }
    - { k: "Socket",      v: "/run/mysqld/mysqld.sock" }
    - { k: "option",      v: "3" }
    - { k: "Charset",     v: "utf8" }
