# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/packages.yml

- name: Update kernel. If this step is 'ok' then no reboot will happen because kernel is up-to-date.
  become: true
  register: rkrn12
  when: ansible_architecture == "x86_64"
  ansible.builtin.apt:
    update_cache: true
    state: latest
    name: linux-image-amd64

- name: Automatically rebooting if necessary. You may need to manually power-up the machine. Script will continue once connection is re-established.
  become: true
  when: rkrn12.changed
  ansible.builtin.reboot:
 
- name: Reboot status check.
  when: rkrn12.changed
  ansible.builtin.debug:
    msg:
     - "**************************************************************************"
     - "* Target rebooted and role should continue automatically until finished. *"
     - "**************************************************************************"

- name: Stay hydrated.
  ansible.builtin.debug:
    msg:
     - "**************************************************************************"
     - "*      Maybe go get a drink of water and come back in 15 minutes ?       *" 
     - "**************************************************************************"

- name: Update packages for Debian 12.
  become: true
  register: rdeb12
  ansible.builtin.apt:
    upgrade: safe

- name: Install packages for Asterisk 20 - mostly per contrib/source/install_prereq file.
  become: true
  register: rast20
  ansible.builtin.apt:
    state: latest
    name:
      - bash
      - binutils-dev
      - bison
      - build-essential
      - bzip2
      - doxygen
      - flex
      - freetds-dev
      - graphviz
      - libasound2-dev
      - libbluetooth-dev
      - libcap-dev
      - libc-client2007e-dev
      - libcfg-dev
      - libcodec2-dev
      - libcorosync-common-dev
      - libcpg-dev
      - libcurl4-openssl-dev
      - libedit-dev
      - libfftw3-dev
      - libgmime-3.0-dev
      - libgsm1-dev
      - libical-dev
      - libiksemel-dev
      - libjack-jackd2-dev
      - libjansson-dev
      - libldap2-dev
      - liblua5.2-dev
      - libmariadb-dev
      - libneon27-dev
      - libnewt-dev
      - libogg-dev
      - libosptk-dev
      - libpopt-dev
      - libpq-dev
      - libradcli-dev
      - libresample1-dev
      - libsndfile1-dev
      - libsnmp-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libsqlite3-dev
      - libsrtp2-dev
      - libssl-dev
      - libunbound-dev
      - liburiparser-dev
      - libvorbis-dev
      - libxml2-dev
      - libxslt1-dev
      - patch
      - pkg-config
      - portaudio19-dev
      - subversion
      - unixodbc-dev
      - uuid-dev
      - wget
      - xmlstarlet
      - zlib1g-dev

- name: Install extra packages for Asterisk 20 for more faxing and codec support.
  become: true
  register: rfax20
  ansible.builtin.apt:
    state: latest
    name:
      - ghostscript
      - imagemagick
      - libjpeg-dev
      - libmp3lame-dev
      - libncurses5-dev
      - libopus-dev
      - libsox-fmt-mp3
      - libspandsp-dev
      - libsystemd-dev
      - libtiff-dev
      - libtiff-tools
      - libxml2-utils

- name: Install DKMS and by extension the kernel header package -- for supporting DAHDI 3.
  become: true
  register: rdhd3
  ansible.builtin.apt:
    state: latest
    name: dkms

- name: Install packages for FreePBX 17.
  become: true
  register: rfpbx17
  ansible.builtin.apt:
    state: latest
    name:
      - apache2
      - git
      - lame
      - mariadb-server
      - mariadb-client
      - mpg123
      - odbc-mariadb
      - nodejs
      - php{{ pngnx_php_version }}
      - php{{ pngnx_php_version }}-curl
      - php{{ pngnx_php_version }}-cli
      - php{{ pngnx_php_version }}-common
      - php{{ pngnx_php_version }}-mysql
      - php{{ pngnx_php_version }}-pgsql
      - php{{ pngnx_php_version }}-gd
      - php{{ pngnx_php_version }}-mbstring
      - php{{ pngnx_php_version }}-intl
      - php{{ pngnx_php_version }}-xml
      - sox
      - sqlite3
      - unixodbc
      - uuid

- name: The PM2 module for FreePBX needs NPM which is HUGE.
  become: true
  register: rnpm
  ansible.builtin.apt:
    state: latest
    name:
      - npm

- name: Install packages that are nice-to-have.
  become: true
  register: rnice
  ansible.builtin.apt:
    state: latest
    name:
      - acl
      - aptitude
      - bc
      - conntrack
      - curl
      - dnsutils
      - dtach
      - ethtool
      - fail2ban
      - gnupg2
      - haveged
      - hwinfo
      - info
      - irqbalance
      - locate
      - lshw
      - man
      - mime-construct
      - mc
      - mutt
      - ncdu
      - net-tools
      - openssh-server
      - opus-tools
      - python3-pymysql
      - rsync
      - rsyslog
      - sip-tester
      - sipsak
      - sngrep
      - snmp
      - sudo
      - tcl
      - tcllib
      - tcl-doc
      - tcl-tclreadline
      - tcpdump
      - tmux
      - ufw
      - vim

# TODO: only when not virtualized
- name: Install packages that are more useful on physical hardware.
  become: true
  register: rphys
  ansible.builtin.apt:
    state: latest
    name:
      - beep
      - irqbalance
      - lm-sensors
      - smartmontools
 
