# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/phoneprov-snom.yml

- name: Snom templates.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.template:
    src: phoneprov/snom/snom320-mac-template.cfg.j2
    dest: /var/lib/asterisk/phoneprov/{{ item }}.cfg
  loop:
    - snom320-mac-template
    - snom320-mac-template-fkeys0_11
    - snom320-mac-template-fkeys2_11
    - snom320-mac-template-fkeys3_11
    - snom320-mac-template-fkeys6_11
    - snom320-mac-template-fkeys3_11-blf6
    - snom320-mac-template-fkeys3_11-blf7
    - snom320-mac-template-fkeys3_11-blfs6_7

- name: More Snom templates.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.template:
    src: phoneprov/snom/snom715-mac-template.cfg.j2
    dest: /var/lib/asterisk/phoneprov/{{ item }}.cfg
  loop:
    - snom715-mac-template
    - snom715-mac-template-fkeys0_4

- name: Snom 320. Adjust the templates to contain the correct function keys 0-11.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys0_11.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(0, 12, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 2-11.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys2_11.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(2, 12, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(3, 12, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 6 and 7. Step 1.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blfs6_7.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(3, 6, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 6 and 7. Step 2.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blfs6_7.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">blf ${FKEY{{ item }}}@{{ pngnx_hostname }}|*8</fkey>'
  loop: "{{ range(6, 8, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 6 and 7. Step 3.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blfs6_7.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(8, 12, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 6. Step 1.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blf6.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(3, 6, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 6. Step 2.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blf6.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">blf ${FKEY{{ item }}}@{{ pngnx_hostname }}|*8</fkey>'
  loop:
    - 6

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 6. Step 3.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blf6.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(8, 12, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 7. Step 1.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blf7.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(3, 6, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 7. Step 2.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blf7.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">blf ${FKEY{{ item }}}@{{ pngnx_hostname }}|*8</fkey>'
  loop:
    - 7

- name: Snom 320. Adjust the templates to contain the correct function keys 3-11. PLUS BLFS ON 7. Step 3.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys3_11-blf7.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(8, 12, 1) | list }}"

- name: Snom 320. Adjust the templates to contain the correct function keys 6-11.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom320-mac-template-fkeys6_11.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(6, 12, 1) | list }}"

- name: Snom 715. Adjust the templates to contain the correct function keys 0-4.
  become: true
  when: pngnx_private_asterisk_phoneprov_dir is not defined
  ansible.builtin.lineinfile:
    dest: /var/lib/asterisk/phoneprov/snom715-mac-template-fkeys0_4.cfg
    regexp: '^<fkey idx="{{ item }}"'
    line: '<fkey idx="{{ item }}" context="active" label="" perm="RW">dest &lt;sip:${FKEY{{ item }}}@{{ pngnx_hostname }};user=phone&gt;</fkey>'
  loop: "{{ range(0, 5, 1) | list }}"
