# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/systemd-asterisk.yml

# Provides automatic start up of Asterisk at boot via SystemD.

- name: Copy SystemD service config files for Asterisk.
  become: yes
  ansible.builtin.copy:
    src: asterisk.service
    dest: /etc/systemd/system/asterisk.service
    owner: root
    group: root
    mode: 0444

- name: Adjust SystemD config to account for maximum channels.
  become: yes
  ansible.builtin.ini_file:
    path: /etc/systemd/system/asterisk.service
    section: Service
    option: ExecStart
    value: /usr/sbin/asterisk -mqf -M {{ pngnx_max_calls | default(7) }} -C /etc/asterisk/asterisk.conf
    no_extra_spaces: yes

- name: Reload SystemD to catch new Asterisk service changes.
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Give SystemD a moment to catch-up.
  delegate_to: localhost
  ansible.builtin.wait_for:
    timeout: 2

- name: Enable Asterisk service via SystemD.
  become: yes
  ansible.builtin.systemd:
    name: asterisk
    enabled: true

- name: Give SystemD another moment to catch-up.
  delegate_to: localhost
  ansible.builtin.wait_for:
    timeout: 2

- name: Start Asterisk service via SystemD.
  become: yes
  ansible.builtin.systemd:
    name: asterisk
    state: started
 
- name: Restart Asterisk. Only when new source build.
  become: yes
  when: pngnx_new_src
  ansible.builtin.service:
    name: asterisk
    enabled: yes   
    state: restarted

