# SPDX-FileCopyrightText: 2023-2024 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/tts-flite.yml

# Text-To-Speech using third-party Flite for Asterisk application

# TODO
# - name: Generate default Flite configuration file for Asterisk.

# TODO
# - name: Provide helper dial plan for Flite (extensions_pngnpbx_tts_flite.conf)

- name: Extra packages for Flite.
  become: true
  ansible.builtin.apt:
    state: present
    name:
      - flite
      - flite1-dev

- name: Make a place for the Flite source.
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.tempfile:
    suffix: ".flite-asterisk"
    state: directory
  register: tmpflt

- name: Download Flite.
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.get_url:
    url: "{{ pngnx_flite_asterisk_urlbase }}"
    dest: "{{ tmpflt.path }}/{{ pngnx_flite_asterisk_zip }}"
    mode: "0500"

- name: Unarchive Flite.
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.unarchive:
    src: "{{ tmpflt.path }}/{{ pngnx_flite_asterisk_zip }}"
    dest: "{{ tmpflt.path }}"
    remote_src: true

- name: Copy Flite source from temp directory to target install directory.
  become: true
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.copy:
    src: "{{ tmpflt.path }}/{{ pngnx_flite_asterisk_basename }}"
    dest: "{{ pngnx_build_target }}"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"

- name: Copy Flite tarball from temp directory to target install directory.
  become: true
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.copy:
    src: "{{ tmpflt.path }}/{{ pngnx_flite_asterisk_zip }}"
    dest: "{{ pngnx_build_target }}"
    remote_src: true
    mode: "0400"

- name: Make Flite.
  when: pngnx_new_src|default(true)|bool
  ansible.builtin.command:
    argv:
      - /usr/bin/make
  args:
    chdir: "{{ pngnx_flite_asterisk_target }}"
  changed_when: true

- name: Install Flite.
  become: true
  when: pngnx_do_asterisk_install|default(true)|bool
  ansible.builtin.command:
    argv:
      - /usr/bin/make
      - install
  args:
    chdir: "{{ pngnx_flite_asterisk_target }}"
  changed_when: true

- name: Make sure needed Asterisk modules are loaded in modules.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/asterisk/modules.conf
    regexp: "{{ item }}"
    line: "load = {{ item }}"
  loop:
    - app_flite.so
