# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/uninstall.yml

# Cleans up most parts of a previous role install.
# uninstall - Keeps Asterisk build, but blows away FreePBX parts.
# splat - Wipes Asterisk, DAHDI and LIBPRI and non-free codecs.
# nopants - Stops and flushes out the firewall parts. Careful!

- name: Disable and Stop FreePBX, Asterisk and Apache.
  become: true
  tags: [never, uninstall, splat]
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - freepbx
    - asterisk
    - apache2
  ignore_errors: true

- name: Remove most of the FreePBX parts.
  become: true
  tags: [never, uninstall, splat]
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/freepbx.conf
    - /etc/amportal.conf
    - /etc/asterisk
    - "{{ pngnx_freepbx_git_target }}"
    - "{{ pngnx_freepbx_edge_target }}"
    - /var/www/html/admin
  ignore_errors: true

- name: Drops the Asterisk MariaDB databases.
  become: true
  tags: [never, uninstall, splat]
  ansible.builtin.command:
    cmd: mysqladmin -f drop {{ item }}
  loop:
    - asterisk
    - asteriskcdrdb
  ignore_errors: true


- name: Disable and Stop MariaDB.
  become: true
  tags: [never, uninstall, splat]
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - mariadb
  ignore_errors: true

- name: Uninstall DAHDI and LIBPRI.
  become: true
  tags: [never, splat]
  ansible.builtin.command:
    cmd: /usr/bin/make uninstall
  args:
    chdir: "{{ item }}"
  loop:
    - "{{ pngnx_libpri_target }}"
    - "{{ pngnx_dahditools_target }}"
    - "{{ pngnx_dahdilinux_target }}"
  ignore_errors: true

- name: Completely uninstall and remove all parts of Asterisk install.
  become: true
  tags: [never, splat]
  ansible.builtin.command:
    cmd: /usr/bin/make uninstall-all
  args:
    chdir: "{{ pngnx_asterisk_target }}"
  ignore_errors: true

- name: Remove source trees for Asterisk, DAHDI and LIBPRI.
  become: true
  tags: [never, splat]
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ pngnx_asterisk_target }}"
    - "{{ pngnx_libpri_target }}"
    - "{{ pngnx_dahditools_target }}"
    - "{{ pngnx_dahdilinux_target }}"
  ignore_errors: true

- name: Remove some more files.
  become: true
  tags: [never, splat]
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/asterisk.makeopts
  ignore_errors: true

- name: Removes non-free codecs if any. TODO fix the rm.
  become: true
  tags: [never, splat]
  ansible.builtin.command:
    cmd: /usr/bin/rm -Rf {{ pngnx_build_target }}/codec_{{ item }}-* # noqa: no-free-form
  with_items: "{{ pngnx_digium_codecs }}"
  ignore_errors: true

- name: Stop and disable fail2ban, ufw, and nftables. Careful!
  become: true
  tags: [never, nopants]
  ansible.builtin.service:
    state: stopped
    enabled: false
  loop:
    - fail2ban
    - ufw
    - nftables
  ignore_errors: true
