# SPDX-FileCopyrightText: 2023 Penguin PBX Solutions <chris at penguin p b x dot com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
---
# file: roles/pngnx23299/tasks/vlan-dns-dhcp.yml

- name: Install arpalert, dnsmasq, resolvconf and vlan packages.
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: present
    name:
      - arpalert
      - dnsmasq
      - resolvconf
      - vlan

- name: Copy over dnsmasq.conf from a template with resolvconf friendly configs.
  become: true
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/pngnx_dhcp_server.conf

- name: Make an entry for the PBX on the VLAN.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "{{ pngnx_vlan_ip }}"
    line: "{{ pngnx_vlan_ip }} pbx.{{ pngnx_vlan_fqdn }} pbx"

- name: Load the VLAN module into the kernel.
  become: true
  ansible.builtin.command: /sbin/modprobe 8021q

# TODO: is everyone using /etc/modules-load.d/*.conf
- name: Make VLAN module load persistent across reboots.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modules
    regexp: "^8021q" 
    line: "8021q" 

- name: Add VLAN to the interfaces.
  become: true
  ansible.builtin.blockinfile:
    path: /etc/network/interfaces.d/pngnx-vlan
    create: true
    block: |
      auto {{ pngnx_vlan_interface }}.{{ pngnx_vlan_id }}
      iface {{ pngnx_vlan_interface }}.{{ pngnx_vlan_id }} inet static
        address {{ pngnx_vlan_ip }}
        netmask {{ pngnx_vlan_netmask }}

- name: Bring up the new VLAN.
  become: true
  ansible.builtin.command: /sbin/ifup {{ pngnx_vlan_interface }}.{{ pngnx_vlan_id }}

- name: Allow phones to send syslogs via UDP on the VLAN.
  become: true
  ansible.builtin.blockinfile:
    path: /etc/rsyslog.d/42-pngnx.conf
    create: true
    block: |
      module(load="imudp")
      input(type="imudp" port="514")

- name: Start dnsmasq on the VLAN.
  become: true
  ignore_errors: true
  service:
    enabled: true
    state: restarted
    name: dnsmasq

